language: php

php:
  - 5.3
  - 5.4

env:
  - DB=mysql
  - DB=pgsql
  - DB=sqlite

before_script:
  - chmod -R 777 ./lib/Cake/Console/cake
  - chmod -R 777 ./app/tmp
  - cp ./app/Config/const.php.default ./app/Config/const.php

script:
  - ./lib/Cake/Console/cake testsuite core AllTests --stderr