language: php

php:
  - 5.3
  - 5.4

env:
  - DB=mysql

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi"
  - chmod -R 777 ./lib/Cake/Console/cake
  - chmod -R 777 ./app/tmp
  - cp ./app/Config/const.php.default ./app/Config/const.php

script:
  - ./lib/Cake/Console/cake testsuite core AllTests --stderr